server:
  port: 8189
  servlet:
    context-path: /api/secure
time-variable:
  accessTokenLifetime: 15m
  refreshTokenLifetime: 7d
  otpCodeLifetime: 15m
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Europe/Moscow
  datasource:
    url: jdbc:postgresql://${AUTH_SERVICE_DB_DOMAIN}:${AUTH_SERVICE_DB_PORT}/auth_service_db
    username: ${AUTH_SERVICE_DB_LOGIN}
    password: ${AUTH_SERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      host: localhost
      port: 6379
