spring:
  application:
    name: cuddle-backend
  config:
    import:
      - classpath:configs/database-config.yml
      - classpath:configs/mail-config.yml
      - classpath:configs/security-config.yml
      - classpath:configs/server-config.yml
      - classpath:configs/other-config.yml