version: '3.7'

services:
  postgres-db:
    image: postgres:15.4-alpine
    container_name: auth_service_db_postgres
    restart: always
    environment:
      POSTGRES_USER: auth_postgres
      POSTGRES_PASSWORD: auth#7533245
      POSTGRES_DB: auth_service_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=512MB
      -c maintenance_work_mem=128MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=8MB
      -c random_page_cost=2
      -c effective_io_concurrency=1
      -c work_mem=8192kB

volumes:
  pgdata:
